### ISSUE TITLE
What is the status of this client?

### ISSUE THREAD

**Issue by kamalmarhubi** [prepor/prometheus-rust#1]
Hi @prepor! I came across this because I was investigating if anyone had already done it. I'm glad someone has!

Could you help me understand the status of this repo? Are you using it in production for any services?

**Comment by prepor** [comment]
Hello! Unfortunately no. It was one of my first attempts to rust, and I realized that properly design even such simple library is pretty hard for me. Now it is definitely not ready for production and I don't have plans to fix it :(

**Comment by kamalmarhubi** [comment]
Thanks for the answer!

**Comment by posix4e** [comment]
I found this!
